apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
